name: math_eng_community
description: A new Flutter project..
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-268.18.beta <3.0.0"
dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.6
  cupertino_icons: ^1.0.2
  firebase: ^9.0.2
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_storage: ^10.2.5
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.3+2
  flutter_screenutil: ^5.1.0
  fluttertoast: ^8.0.8
  image_picker: ^0.8.4+4
  kartal: ^2.3.1
  lottie: ^1.2.1
  mobx: ^2.0.6+1
  mobx_codegen: ^2.0.5+2
  syncfusion_flutter_pdfviewer: ^19.4.43-beta
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - asset/images/
    - asset/lottie/
